### ISSUE TITLE
The issue with colours has been fixed!

### ISSUE THREAD

**Issue by 00-kat** [rose-pine/ghostty#2]
https://github.com/mbadolato/iTerm2-Color-Schemes/pull/485

However, this won't be pulled in by Ghostty until the end of the week, so there's a chance that it won't be applied in time for v1.0.1, unless an update is triggered manually by Mitchell.

**Comment by mvllow** [comment]
Looks like it was updated 1 minute ago via https://github.com/ghostty-org/ghostty/pull/4152 :)

**Comment by 00-kat** [comment]
Yep I had just asked Mitchell if he could trigger an update ^^

There was talk about v1.0.1 being released around midday tomorrow, so maybe after that the note in the README could mention that upgrading to that version would fix it.

**Comment by mvllow** [comment]
Oh lovely, thanks for doing that! I'll update the readme once released

**Comment by Gelmo** [comment]
Yay :D

**Comment by 00-kat** [comment]
Actually, it appears I was incorrect and that https://github.com/mbadolato/iTerm2-Color-Schemes/pull/485 only partially fixes it...  It had looked fine from a cursory glance at the diff but for some reason, Rosé Pine Dawn has it fixed properly, Rosé Pine Moon has the brights and the selection fixed, and Rosé Pine only has the selection fixed.
